# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CoordCalc
                                 A QGIS plugin
 Calculadora para realizar conversiones entre latitud y longitud, decimales, coordenadas UTM 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-04-18
        copyright            : (C) 2021 by Yessi Murcia 
        email                : yessi.murcia03@unah.hn
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CoordCalc class from file CoordCalc.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .coordcalc import CoordCalc
    return CoordCalc(iface)
